openapi: 3.0.0
paths:
  {% if features.generic %}
  '/db/{{database}}/{{view}}':
    get:
      tags:
        - db_{{database}}
        - query_generic
      parameters:
        - $ref: '#/components/parameters/returnQuery'
        {%- for arg in args %}
        - $ref: '#/components/parameters/arg_{{database}}_{{view}}_{{arg.name}}'
        {%- endfor %}
        {%- for filter in filters %}
        - $ref: '#/components/parameters/filter_{{database}}_{{view}}_filter_{{filter}}'
        {%- endfor %}
      responses:
        '200':
          $ref: '#/components/responses/entries_{{database}}_{{view}}'
        '403':
          $ref: '#/components/responses/notAllowed'
        '404':
          $ref: '#/components/responses/notFound'
  {%- endif %}
  {% if features.csv %}
  '/db/{{database}}/{{view}}.csv':
    get:
      tags:
        - db_{{database}}
        - query_generic
      parameters:
        {%- for arg in args %}
        - $ref: '#/components/parameters/arg_{{database}}_{{view}}_{{arg.name}}'
        {%- endfor %}
        {%- for filter in filters %}
        - $ref: '#/components/parameters/filter_{{database}}_{{view}}_filter_{{filter}}'
        {%- endfor %}
      responses:
        '200':
          $ref: '#/components/responses/csv'
        '403':
          $ref: '#/components/responses/notAllowed'
        '404':
          $ref: '#/components/responses/notFound'
  {%- endif %}
  {% if features.count %}
  '/db/{{database}}/{{view}}/count':
    get:
      tags:
        - db_{{database}}
        - query_generic
      parameters:
        - $ref: '#/components/parameters/returnQuery'
        {%- for arg in args %}
        - $ref: '#/components/parameters/arg_{{database}}_{{view}}_{{arg.name}}'
        {%- endfor %}
        {%- for filter in filters %}
        - $ref: '#/components/parameters/filter_{{database}}_{{view}}_filter_{{filter}}'
        {%- endfor %}
      responses:
        '200':
          $ref: '#/components/responses/queryCount'
        '403':
          $ref: '#/components/responses/notAllowed'
        '404':
          $ref: '#/components/responses/notFound'
  {%- endif %}
  {% if features.desc %}
  '/db/{{database}}/{{view}}/desc':
    get:
      tags:
        - db_{{database}}
        - query_generic
      responses:
        '200':
          $ref: '#/components/responses/queryDesc'
        '403':
          $ref: '#/components/responses/notAllowed'
        '404':
          $ref: '#/components/responses/notFound'
  {%- endif %}
  {% if features.lookup %}
  '/db/{{database}}/{{view}}/lookup':
    get:
      tags:
        - db_{{database}}
        - query_lookup
      parameters:
        - $ref: '#/components/parameters/lookupQuery'
        - $ref: '#/components/parameters/lookupPage'
        - $ref: '#/components/parameters/lookupLimit'
      responses:
        '200':
          $ref: '#/components/responses/queryLookup'
        '403':
          $ref: '#/components/responses/notAllowed'
        '404':
          $ref: '#/components/responses/notFound'
  {%- endif %}
  {% if features.score %}
  '/db/{{database}}/{{view}}/score':
    get:
      tags:
        - db_{{database}}
        - query_score
      parameters:
        - $ref: '#/components/parameters/scoreTarget'
        - $ref: '#/components/parameters/returnQuery'
        {%- for arg in args %}
        - $ref: '#/components/parameters/arg_{{database}}_{{view}}_{{arg.name}}'
        {%- endfor %}
        {%- for filter in filters %}
        - $ref: '#/components/parameters/filter_{{database}}_{{view}}_filter_{{filter}}'
        {%- endfor %}
      responses:
        '200':
          $ref: '#/components/responses/queryScore'
        '403':
          $ref: '#/components/responses/notAllowed'
        '404':
          $ref: '#/components/responses/notFound'
  {%- endif %}


components:
  parameters: {% if empty %}{}{% endif %}
    {%- for arg in args %}
    'arg_{{database}}_{{view}}_{{arg.name}}':
      name: '{{arg.name}}'
      required: true
      in: query
      schema:
        {% if arg.as_list == false %}type: {{arg.type}}{% endif %}
        {% if arg.as_list %}type: array
        minLength: 1
        items:
          type: {{arg.type}}
      style: form
        {%- endif %}
        {% if arg.enum %}
        enum:
          {% for e in arg.enum %}- '{% if e.name %}{{e.name}}{% else %}{{e}}{% endif %}'
          {% endfor %}
      {%- endif %}
    {%- endfor %}
    {%- for filter in filters %}
    'filter_{{database}}_{{view}}_filter_{{filter}}':
      name: filter_{{filter}}
      required: false
      in: query
      schema:
        type: array
        items:
          type: string
        minLength: 1
      style: form
    {%- endfor %}
  responses:
    entries_{{database}}_{{view}}:
      description: Successful response
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/entry_{{database}}_{{view}}'
            #oneOf:
            #  - $ref: '#/components/schemas/returnQuery'

  schemas:
    entry_{{database}}_{{view}}:
      type: object
      properties:
      {%- for prop in props %}
        '{{prop.name}}':
          type: {{prop.type}}
          {% if prop.categories %}
          enum:
            {% for e in prop.categories %}- '{% if e.name %}{{e.name}}{% else %}{{e}}{% endif %}'
            {% endfor %}
          {%- endif %}
          {% if prop.min %}
          minimum: {{prop.min}}
          maximum: {{prop.max}}
          {%- endif %}
      {%- endfor %}
      additionalProperties: true
